### ISSUE TITLE
how to add new plugins?

### ISSUE THREAD

**Issue by hadifarnoud** [fastmonkeys/sentry-on-heroku#23]
in Docker deploy, I have to add plugins to requirements.txt and build the image. in regular server install, I just do `pip install`

how can I add plugins on heroku?

**Comment by jpvanhal** [comment]
1. Fork the repo.
2. Install [`pip-tools`](https://github.com/nvie/pip-tools)
3. Add the plugin to `requirements.in`.
4. Run `pip-compile --output-file requirements.txt requirements.in` to update the `requirements.txt` file.
5. Commit changes.
6. Push to Heroku.

**Comment by hadifarnoud** [comment]
I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/piptools/scripts/compile.py", line 195, in cli
    reverse_dependencies = resolver.reverse_dependencies(results)
  File "/usr/local/lib/python2.7/site-packages/piptools/resolver.py", line 267, in reverse_dependencies
    return self.dependency_cache.reverse_dependencies(non_editable)
  File "/usr/local/lib/python2.7/site-packages/piptools/cache.py", line 139, in reverse_dependencies
    return self._reverse_dependencies(ireqs_as_cache_values)
  File "/usr/local/lib/python2.7/site-packages/piptools/cache.py", line 163, in _reverse_dependencies
    for name, version_and_extras in cache_keys
  File "/usr/local/lib/python2.7/site-packages/piptools/utils.py", line 191, in lookup_table
    for value in values:
  File "/usr/local/lib/python2.7/site-packages/piptools/cache.py", line 164, in <genexpr>
    for dep_name in self.cache[name][version_and_extras])
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3044, in parse
    req, = parse_requirements(s)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2988, in parse_requirements
    "version spec")
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2953, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pkg_resources.RequirementParseError: Expected version spec in ndg-httpsclient; extra == "security" at ; extra == "security"
```

**Comment by hadifarnoud** [comment]
my requirements.in file:
```
dj-database-url
django-bcrypt
django-secure
ndg-httpsclient  # required by requests
psycopg2
sentry
sentry-flowdock
sentry-github
sentry-sprintly
sentry-searchbutton
```

**Comment by jpvanhal** [comment]
I couldn't reproduce that issue. Maybe your pip is too old. pip-tools requires at least v6.1.

**Comment by hadifarnoud** [comment]
was my fault. I modified it to make it Flynn ready.
